#!/usr/bin/env python3
"""Generate a concise architecture and contribution-rules profile for a repository."""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path


KEY_FILES = [
    "AGENTS.md",
    "README.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    ".gitcode/PULL_REQUEST_TEMPLATE.zh-CN.md",
    ".pre-commit-config.yaml",
    ".clang-format",
    "CMakeLists.txt",
    "build.sh",
    "requirements.txt",
]


def run(repo: Path, *args: str) -> str:
    try:
        return subprocess.check_output(args, cwd=repo, text=True, stderr=subprocess.DEVNULL).strip()
    except Exception:
        return ""


def read_head(path: Path, limit: int = 80) -> str:
    if not path.exists() or not path.is_file():
        return ""
    try:
        lines = path.read_text(encoding="utf-8-sig", errors="replace").splitlines()
    except OSError:
        return ""
    return "\n".join(lines[:limit])


def tree(repo: Path, max_depth: int = 2) -> list[str]:
    ignored = {".git", "build", "dist", "__pycache__", ".venv", "node_modules"}
    rows: list[str] = []
    for path in sorted(repo.rglob("*")):
        rel = path.relative_to(repo)
        parts = rel.parts
        if len(parts) > max_depth or any(part in ignored for part in parts):
            continue
        rows.append(f"- `{rel.as_posix()}/`" if path.is_dir() else f"- `{rel.as_posix()}`")
    return rows[:220]


def section(title: str, body: str) -> str:
    return f"## {title}\n\n{body.strip()}\n"


def infer_stack(repo: Path) -> list[str]:
    stack: list[str] = []
    if (repo / "CMakeLists.txt").exists():
        stack.append("CMake/C++")
    if (repo / "build.sh").exists():
        stack.append("project build.sh workflow")
    if (repo / "requirements.txt").exists() or (repo / "pyproject.toml").exists():
        stack.append("Python tooling")
    if (repo / ".pre-commit-config.yaml").exists():
        stack.append("pre-commit")
    if (repo / ".clang-format").exists():
        stack.append("clang-format")
    if (repo / ".gitcode").exists():
        stack.append("GitCode templates/workflows")
    return stack


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", default=".", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    repo = args.repo.resolve()
    out = args.output if args.output.is_absolute() else repo / args.output
    remote = run(repo, "git", "remote", "get-url", "origin")
    branch = run(repo, "git", "branch", "--show-current")
    stack = infer_stack(repo)

    parts: list[str] = [
        "# Architecture and Contribution Rules",
        "",
        "> Generated by `gitcode-issue-fix`. Review and refine before treating this as authoritative.",
        "",
        section(
            "Repository Snapshot",
            "\n".join(
                [
                    f"- Repository: `{repo.name}`",
                    f"- Origin: `{remote or 'unknown'}`",
                    f"- Current branch: `{branch or 'unknown'}`",
                    f"- Detected stack: {', '.join(stack) if stack else 'unknown'}",
                ]
            ),
        ),
        section("Top-Level Architecture", "\n".join(tree(repo)) or "No files detected."),
    ]

    notes = []
    for name in KEY_FILES:
        text = read_head(repo / name)
        if text:
            notes.append(f"### `{name}`\n\n```text\n{text}\n```")
    parts.append(section("Relevant Local Rules and Configs", "\n\n".join(notes) or "No key rule files detected."))

    issue_templates = sorted((repo / ".gitcode" / "ISSUE_TEMPLATE").glob("*")) if (repo / ".gitcode" / "ISSUE_TEMPLATE").exists() else []
    pr_templates = sorted((repo / ".gitcode").glob("PULL_REQUEST_TEMPLATE*")) if (repo / ".gitcode").exists() else []
    workflows = sorted((repo / ".gitcode" / "workflows").glob("*")) if (repo / ".gitcode" / "workflows").exists() else []
    parts.append(
        section(
            "GitCode Collaboration Surface",
            "\n".join(
                [
                    "Issue templates:",
                    *(f"- `{p.relative_to(repo).as_posix()}`" for p in issue_templates),
                    "",
                    "PR templates:",
                    *(f"- `{p.relative_to(repo).as_posix()}`" for p in pr_templates),
                    "",
                    "Workflows:",
                    *(f"- `{p.relative_to(repo).as_posix()}`" for p in workflows),
                ]
            ).strip()
            or "No GitCode templates/workflows detected.",
        )
    )

    parts.append(
        section(
            "Contribution Checklist",
            "\n".join(
                [
                    "- Start from a clean or consciously preserved worktree.",
                    "- Open an issue before non-trivial features, API changes, configuration changes, or behavior changes.",
                    "- Use repository issue and PR templates exactly.",
                    "- Keep fixes minimal and add focused tests or static checks.",
                    "- Run formatting, build, unit tests, and project CI equivalents before opening PR.",
                    "- Record skipped checks with exact environment blockers.",
                ]
            ),
        )
    )

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")
    print(out)


if __name__ == "__main__":
    main()
